package levels

import (
	"dungeoneer/sprites"
	"dungeoneer/tiles"
	"image/color"

	"github.com/hajimehoshi/ebiten/v2"
)

var grassGreen = color.RGBA64{G: 255, R: 0, B: 0, A: 10}
var ss, _ = sprites.LoadSpriteSheet(64)
var LEVEL_ONE = &Level{
	W:        16,
	H:        16,
	TileSize: 64,
	Tiles: [][]*tiles.Tile{
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
		[]*tiles.Tile{
			&tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}, &tiles.Tile{Sprites: []*ebiten.Image{ss.Floor}}},
	},
}
