package sprites

import (
	"dungeoneer/images"
	"image"
	_ "image/png"

	"github.com/hajimehoshi/ebiten/v2"
)

// SpriteSheet represents a collection of sprite images.
type SpriteSheet struct {
	//Row Index 0
	Void        *ebiten.Image // (0, 0)
	OakBeam     *ebiten.Image // (1, 0)
	OakBeamNW   *ebiten.Image // (2, 0)
	OakBeamNE   *ebiten.Image // (3, 0)
	OakLog      *ebiten.Image // (4, 0)
	OakBeamSW   *ebiten.Image // (5, 0)
	OakLogSlim  *ebiten.Image // (6, 0)
	OakBeamNESW *ebiten.Image // (7, 0)
	OakLogNE    *ebiten.Image // (8, 0)
	OakBeamSE   *ebiten.Image // (9, 0)
	OakLogNWSE  *ebiten.Image // (10, 0)
	OakLogSlim2 *ebiten.Image // (11, 0)
	OakWallNESW *ebiten.Image // (12, 0)
	OakWall     *ebiten.Image // (13, 0)
	OakWallNWSE *ebiten.Image // (14, 0)
	OakLogSW    *ebiten.Image // (15, 0)

	//Row Index 1
	OakChunk         *ebiten.Image // (0, 1)
	MarbleBeam       *ebiten.Image // (1, 1)
	MarbleBeamNW     *ebiten.Image // (2, 1)
	MarbleBeamNE     *ebiten.Image // (3, 1)
	MarbleWall       *ebiten.Image // (4, 1)
	MarbleBeamNE2    *ebiten.Image // (5, 1)
	MarbleWall2      *ebiten.Image // (6, 1)
	MarbleBeamNELong *ebiten.Image // (7, 1)
	MarbleWallNELong *ebiten.Image // (8, 1)
	MarbleBeamNW2    *ebiten.Image // (9, 1)
	MarbleBeamNWLong *ebiten.Image // (10, 1)
	MarbleWall3      *ebiten.Image // (11, 1)
	MarbleWallNWLong *ebiten.Image // (12, 1)
	MarbleWall4      *ebiten.Image // (13, 1)
	MarbleWallNW     *ebiten.Image // (14, 1)
	MarbleWallNE     *ebiten.Image // (15, 1)

	//Row Index 2
	MarbleChunk       *ebiten.Image // (0, 2)
	LockedDoorNW      *ebiten.Image // (1, 2)
	LockedDoorNE      *ebiten.Image // (2, 2)
	DungeonBeam       *ebiten.Image // (3, 2)
	DungeonBeamNW     *ebiten.Image // (4, 2)
	DungeonBeamNE     *ebiten.Image // (5, 2)
	DungeonWall       *ebiten.Image // (6, 2)
	DungeonBeamNE2    *ebiten.Image // (7, 2)
	DungeonWall2      *ebiten.Image // (8, 2)
	DungeonBeamNELong *ebiten.Image // (9, 2)
	DungeonWallNELong *ebiten.Image // (10, 2)
	DungeonBeamNW2    *ebiten.Image // (11, 2)
	DungeonBeamNWLong *ebiten.Image // (12, 2)
	DungeonWall3      *ebiten.Image // (13, 2)
	DungeonWallNWLong *ebiten.Image // (14, 2)
	DungeonWall4      *ebiten.Image // (15, 2)

	//Row Index 3
	DungeonWallNWLong2 *ebiten.Image // (0, 3)
	DungeonWallNELong2 *ebiten.Image // (1, 3)
	DungeonChunk       *ebiten.Image // (2, 3)
	EmeraldBeam        *ebiten.Image // (3, 3)
	EmeraldBeamNW      *ebiten.Image // (4, 3)
	EmeraldBeamNE      *ebiten.Image // (5, 3)
	EmeraldWall        *ebiten.Image // (6, 3)
	EmeraldBeamNE2     *ebiten.Image // (7, 3)
	EmeraldWall2       *ebiten.Image // (8, 3)
	EmeraldBeamNELong  *ebiten.Image // (9, 3)
	EmeraldWallNELong  *ebiten.Image // (10, 3)
	EmeraldBeamNW2     *ebiten.Image // (11, 3)
	EmeraldBeamNWLong  *ebiten.Image // (12, 3)
	EmeraldWall3       *ebiten.Image // (13, 3)
	EmeraldWallNWLong  *ebiten.Image // (14, 3)
	EmeraldWall4       *ebiten.Image // (15, 3)

	//Row Index 4
	EmerladWallNWLong2 *ebiten.Image // (0, 4)
	EmerladWallNELong2 *ebiten.Image // (1, 4)
	EmerladChunk       *ebiten.Image // (2, 4)
	Well               *ebiten.Image // (3, 4)
	DragonStatue       *ebiten.Image // (4, 4)
	Statue             *ebiten.Image // (5, 4)
	ChaosStatue        *ebiten.Image // (6, 4)
	Lava               *ebiten.Image // (7, 4)
	Water              *ebiten.Image // (8, 4)
	EnchantedWater     *ebiten.Image // (9, 4)
	Floor              *ebiten.Image // (10, 4)
	UnlockedDoorNW     *ebiten.Image // (11, 4)
	UnlockedDoorNE     *ebiten.Image // (12, 4)
	StairsDecending    *ebiten.Image // (13, 4)
	FloorTrap          *ebiten.Image // (14, 4)
	Pentagram          *ebiten.Image // (15, 4)

	//Row Index 5
	SkullHex               *ebiten.Image // (0, 5)
	StairsDecending2       *ebiten.Image // (1, 5)
	StairsDecending3       *ebiten.Image // (2, 5)
	StairsDecending4       *ebiten.Image // (3, 5)
	StairsDecending5       *ebiten.Image // (4, 5)
	StairsAscending        *ebiten.Image // (5, 5)
	StairsAscending2       *ebiten.Image // (6, 5)
	StairsAscending3       *ebiten.Image // (7, 5)
	StairsAscending4       *ebiten.Image // (8, 5)
	StairsDescendingYellow *ebiten.Image // (9, 5)
	StairsAscendingYellow  *ebiten.Image // (10, 5)
	ArchGlitch             *ebiten.Image // (11, 5)
	ArchBlack              *ebiten.Image // (12, 5)
	ArchRed                *ebiten.Image // (13, 5)
	ArchBlue               *ebiten.Image // (14, 5)
	ArchGreen              *ebiten.Image // (15, 5)

	//Row Index 6
	ArchDeath    *ebiten.Image // (0, 6)
	ArchStar     *ebiten.Image // (1, 6)
	ArchEmpty    *ebiten.Image // (2, 6)
	ArchBoss     *ebiten.Image // (3, 6)
	ArchStar2    *ebiten.Image // (4, 6)
	Portal       *ebiten.Image // (5, 6)
	ArchDark     *ebiten.Image // (6, 6)
	HandOfGod    *ebiten.Image // (7, 6)
	GoldenStatue *ebiten.Image // (8, 6)
	DeadPile     *ebiten.Image // (9, 6)
	DeadHanging  *ebiten.Image // (10, 6)
	SansStatue   *ebiten.Image // (11, 6)
	Glyph        *ebiten.Image // (12, 6)
	DeathMarker  *ebiten.Image // (13, 6)
	Campfire     *ebiten.Image // (14, 6)
	GlyphStatue  *ebiten.Image // (15, 6)

	//Row Index 7
	DecapitatedHead *ebiten.Image // (0, 7)
	GrandChest      *ebiten.Image // (1, 7)
	Chalice         *ebiten.Image // (2, 7)
	Trinket         *ebiten.Image // (3, 7)
	GreyKnight      *ebiten.Image // (4, 7)
	Chimera         *ebiten.Image // (5, 7)
	Sentinel        *ebiten.Image // (6, 7)
	Sorcerer        *ebiten.Image // (7, 7)
	Duchess         *ebiten.Image // (8, 7)
	Absolem         *ebiten.Image // (9, 7)
	Death           *ebiten.Image // (10, 7)
	Oracle          *ebiten.Image // (11, 7)
	Jester          *ebiten.Image // (12, 7)
	GreaterDemon    *ebiten.Image // (13, 7)
	DemonKnight     *ebiten.Image // (14, 7)
	Abomination     *ebiten.Image // (15, 7)

	//Row Index 8
	QueenOfDarkness *ebiten.Image // (0, 8)
	LesserDemon     *ebiten.Image // (1, 8)
	TheTerror       *ebiten.Image // (2, 8)
	Celestial       *ebiten.Image // (3, 8)
	Demon           *ebiten.Image // (4, 8)
	Apparition      *ebiten.Image // (5, 8)
	Griffon         *ebiten.Image // (6, 8)
	Manticore       *ebiten.Image // (7, 8)
	Minotaur        *ebiten.Image // (8, 8)
	TorturedSoul    *ebiten.Image // (9, 8)
	ChaosTotem      *ebiten.Image // (10, 8)
	HydraBase       *ebiten.Image // (11, 8)
	Hydra2          *ebiten.Image // (12, 8)
	Hydra3          *ebiten.Image // (13, 8)
	Hydra4          *ebiten.Image // (14, 8)
	Hydra5          *ebiten.Image // (15, 8)

	//Row Index 9
	Hydra6             *ebiten.Image // (0, 9)
	HydraFinal         *ebiten.Image // (1, 9)
	LesserDragon       *ebiten.Image // (2, 9)
	GoldenDragon       *ebiten.Image // (3, 9)
	Wyvern             *ebiten.Image // (4, 9)
	LesserCaveDragon   *ebiten.Image // (5, 9)
	GhostWyvern        *ebiten.Image // (6, 9)
	AncientDragonRed   *ebiten.Image // (7, 9)
	AncientDragonBlack *ebiten.Image // (8, 9)
	AncientDragon      *ebiten.Image // (9, 9)
	PetrifiedDragon    *ebiten.Image // (10, 9)
	GreaterDragon      *ebiten.Image // (11, 9)
	GreaterRedDragon   *ebiten.Image // (12, 9)
	BlueMan            *ebiten.Image // (13, 9)
	Cyclops            *ebiten.Image // (14, 9)
	TwoHeadedOgre      *ebiten.Image // (15, 9)

	//Row Index 10
	RedChampion   *ebiten.Image // (0, 10)
	BlueChampion  *ebiten.Image // (1, 10)
	Caveman       *ebiten.Image // (2, 10)
	RockCollector *ebiten.Image // (3, 10)
	RedMan        *ebiten.Image // (4, 10)
	Cursor        *ebiten.Image // (5, 10)
	EnemyCursor   *ebiten.Image // (6, 10)
	NullSprite    *ebiten.Image // (7, 10)
	FireBurst     *ebiten.Image // (8, 10)
	FireBurst2    *ebiten.Image // (9, 10)
	FireBurst3    *ebiten.Image // (10, 10)
	ArcaneBurst   *ebiten.Image // (11, 10)
	ArcaneBurst2  *ebiten.Image // (12, 10)
	ArcaneBurst3  *ebiten.Image // (13, 10)
	PosionBurst   *ebiten.Image // (14, 10)
	PosionBurst2  *ebiten.Image // (15, 10)

	//Row Index 11
	PosionBurst3 *ebiten.Image // (0, 11)
	Smoke        *ebiten.Image // (1, 11)
	BlueSmoke    *ebiten.Image // (2, 11)
	BigSmoke     *ebiten.Image // (3, 11)
	Smoke2       *ebiten.Image // (4, 11)
	PurpleSmoke  *ebiten.Image // (5, 11)
	Trap         *ebiten.Image // (6, 11)

	// Walls stores additional wall palettes that can be used for level generation.
	// The key is the flavor name (e.g. "stone", "brick"), and the value is a
	// WallSpriteSheet loaded from the embedded resources.
	Walls map[string]*WallSpriteSheet
}

// LoadSpriteSheet loads the embedded SpriteSheet.
func LoadSpriteSheet(tileSize int) (*SpriteSheet, error) {
	sheet, err := images.LoadEmbeddedImage(images.Spritesheet_png)
	if err != nil {
		return nil, err
	}

	// spriteAt returns a sprite at the provided coordinates.
	spriteAt := func(x, y int) *ebiten.Image {
		return sheet.SubImage(image.Rect(x*tileSize, (y+1)*tileSize, (x+1)*tileSize, y*tileSize)).(*ebiten.Image)
	}

	// Populate SpriteSheet.

	s := &SpriteSheet{} // <– Init map

	s.Walls = make(map[string]*WallSpriteSheet)
	s.Void = spriteAt(0, 0)
	s.OakBeam = spriteAt(1, 0)
	s.OakBeamNW = spriteAt(2, 0)
	s.OakBeamNE = spriteAt(3, 0)
	s.OakLog = spriteAt(4, 0)
	s.OakBeamSW = spriteAt(5, 0)
	s.OakLogSlim = spriteAt(6, 0)
	s.OakBeamNESW = spriteAt(7, 0)
	s.OakLogNE = spriteAt(8, 0)
	s.OakBeamSE = spriteAt(9, 0)
	s.OakLogNWSE = spriteAt(10, 0)
	s.OakLogSlim2 = spriteAt(11, 0)
	s.OakWallNESW = spriteAt(12, 0)
	s.OakWall = spriteAt(13, 0)
	s.OakWallNWSE = spriteAt(14, 0)
	s.OakLogSW = spriteAt(15, 0)

	//Row Index 1
	s.OakChunk = spriteAt(0, 1)
	s.MarbleBeam = spriteAt(1, 1)
	s.MarbleBeamNW = spriteAt(2, 1)
	s.MarbleBeamNE = spriteAt(3, 1)
	s.MarbleWall = spriteAt(4, 1)
	s.MarbleBeamNE2 = spriteAt(5, 1)
	s.MarbleWall2 = spriteAt(6, 1)
	s.MarbleBeamNELong = spriteAt(7, 1)
	s.MarbleWallNELong = spriteAt(8, 1)
	s.MarbleBeamNW2 = spriteAt(9, 1)
	s.MarbleBeamNWLong = spriteAt(10, 1)
	s.MarbleWall3 = spriteAt(11, 1)
	s.MarbleWallNWLong = spriteAt(12, 1)
	s.MarbleWall4 = spriteAt(13, 1)
	s.MarbleWallNW = spriteAt(14, 1)
	s.MarbleWallNE = spriteAt(15, 1)

	//Row Index 2
	s.MarbleChunk = spriteAt(0, 2)
	s.LockedDoorNW = spriteAt(1, 2)
	s.LockedDoorNE = spriteAt(2, 2)
	s.DungeonBeam = spriteAt(3, 2)
	s.DungeonBeamNW = spriteAt(4, 2)
	s.DungeonBeamNE = spriteAt(5, 2)
	s.DungeonWall = spriteAt(6, 2)
	s.DungeonBeamNE2 = spriteAt(7, 2)
	s.DungeonWall2 = spriteAt(8, 2)
	s.DungeonBeamNELong = spriteAt(9, 2)
	s.DungeonWallNELong = spriteAt(10, 2)
	s.DungeonBeamNW2 = spriteAt(11, 2)
	s.DungeonBeamNWLong = spriteAt(12, 2)
	s.DungeonWall3 = spriteAt(13, 2)
	s.DungeonWallNWLong = spriteAt(14, 2)
	s.DungeonWall4 = spriteAt(15, 2)

	//Row Index 3
	s.DungeonWallNWLong2 = spriteAt(0, 3)
	s.DungeonWallNELong2 = spriteAt(1, 3)
	s.DungeonChunk = spriteAt(2, 3)
	s.EmeraldBeam = spriteAt(3, 3)
	s.EmeraldBeamNW = spriteAt(4, 3)
	s.EmeraldBeamNE = spriteAt(5, 3)
	s.EmeraldWall = spriteAt(6, 3)
	s.EmeraldBeamNE2 = spriteAt(7, 3)
	s.EmeraldWall2 = spriteAt(8, 3)
	s.EmeraldBeamNELong = spriteAt(9, 3)
	s.EmeraldWallNELong = spriteAt(10, 3)
	s.EmeraldBeamNW2 = spriteAt(11, 3)
	s.EmeraldBeamNWLong = spriteAt(12, 3)
	s.EmeraldWall3 = spriteAt(13, 3)
	s.EmeraldWallNWLong = spriteAt(14, 3)
	s.EmeraldWall4 = spriteAt(15, 3)

	//Row Index 4
	s.EmerladWallNWLong2 = spriteAt(0, 4)
	s.EmerladWallNELong2 = spriteAt(1, 4)
	s.EmerladChunk = spriteAt(2, 4)
	s.Well = spriteAt(3, 4)
	s.DragonStatue = spriteAt(4, 4)
	s.Statue = spriteAt(5, 4)
	s.ChaosStatue = spriteAt(6, 4)
	s.Lava = spriteAt(7, 4)
	s.Water = spriteAt(8, 4)
	s.EnchantedWater = spriteAt(9, 4)
	s.Floor = spriteAt(10, 4)
	s.UnlockedDoorNW = spriteAt(11, 4)
	s.UnlockedDoorNE = spriteAt(12, 4)
	s.StairsDecending = spriteAt(13, 4)
	s.FloorTrap = spriteAt(14, 4)
	s.Pentagram = spriteAt(15, 4)

	//Row Index 5
	s.SkullHex = spriteAt(0, 5)
	s.StairsDecending2 = spriteAt(1, 5)
	s.StairsDecending3 = spriteAt(2, 5)
	s.StairsDecending4 = spriteAt(3, 5)
	s.StairsDecending5 = spriteAt(4, 5)
	s.StairsAscending = spriteAt(5, 5)
	s.StairsAscending2 = spriteAt(6, 5)
	s.StairsAscending3 = spriteAt(7, 5)
	s.StairsAscending4 = spriteAt(8, 5)
	s.StairsDescendingYellow = spriteAt(9, 5)
	s.StairsAscendingYellow = spriteAt(10, 5)
	s.ArchGlitch = spriteAt(11, 5)
	s.ArchBlack = spriteAt(12, 5)
	s.ArchRed = spriteAt(13, 5)
	s.ArchBlue = spriteAt(14, 5)
	s.ArchGreen = spriteAt(15, 5)

	//Row Index 6
	s.ArchDeath = spriteAt(0, 6)
	s.ArchStar = spriteAt(1, 6)
	s.ArchEmpty = spriteAt(2, 6)
	s.ArchBoss = spriteAt(3, 6)
	s.ArchStar2 = spriteAt(4, 6)
	s.Portal = spriteAt(5, 6)
	s.ArchDark = spriteAt(6, 6)
	s.HandOfGod = spriteAt(7, 6)
	s.GoldenStatue = spriteAt(8, 6)
	s.DeadPile = spriteAt(9, 6)
	s.DeadHanging = spriteAt(10, 6)
	s.SansStatue = spriteAt(11, 6)
	s.Glyph = spriteAt(12, 6)
	s.DeathMarker = spriteAt(13, 6)
	s.Campfire = spriteAt(14, 6)
	s.GlyphStatue = spriteAt(15, 6)

	//Row Index 7
	s.DecapitatedHead = spriteAt(0, 7)
	s.GrandChest = spriteAt(1, 7)
	s.Chalice = spriteAt(2, 7)
	s.Trinket = spriteAt(3, 7)
	s.GreyKnight = spriteAt(4, 7)
	s.Chimera = spriteAt(5, 7)
	s.Sentinel = spriteAt(6, 7)
	s.Sorcerer = spriteAt(7, 7)
	s.Duchess = spriteAt(8, 7)
	s.Absolem = spriteAt(9, 7)
	s.Death = spriteAt(10, 7)
	s.Oracle = spriteAt(11, 7)
	s.Jester = spriteAt(12, 7)
	s.GreaterDemon = spriteAt(13, 7)
	s.DemonKnight = spriteAt(14, 7)
	s.Abomination = spriteAt(15, 7)

	//Row Index 8
	s.QueenOfDarkness = spriteAt(0, 8)
	s.LesserDemon = spriteAt(1, 8)
	s.TheTerror = spriteAt(2, 8)
	s.Celestial = spriteAt(3, 8)
	s.Demon = spriteAt(4, 8)
	s.Apparition = spriteAt(5, 8)
	s.Griffon = spriteAt(6, 8)
	s.Manticore = spriteAt(7, 8)
	s.Minotaur = spriteAt(8, 8)
	s.TorturedSoul = spriteAt(9, 8)
	s.ChaosTotem = spriteAt(10, 8)
	s.HydraBase = spriteAt(11, 8)
	s.Hydra2 = spriteAt(12, 8)
	s.Hydra3 = spriteAt(13, 8)
	s.Hydra4 = spriteAt(14, 8)
	s.Hydra5 = spriteAt(15, 8)

	//Row Index 9
	s.Hydra6 = spriteAt(0, 9)
	s.HydraFinal = spriteAt(1, 9)
	s.LesserDragon = spriteAt(2, 9)
	s.GoldenDragon = spriteAt(3, 9)
	s.Wyvern = spriteAt(4, 9)
	s.LesserCaveDragon = spriteAt(5, 9)
	s.GhostWyvern = spriteAt(6, 9)
	s.AncientDragonRed = spriteAt(7, 9)
	s.AncientDragonBlack = spriteAt(8, 9)
	s.AncientDragon = spriteAt(9, 9)
	s.PetrifiedDragon = spriteAt(10, 9)
	s.GreaterDragon = spriteAt(11, 9)
	s.GreaterRedDragon = spriteAt(12, 9)
	s.BlueMan = spriteAt(13, 9)
	s.Cyclops = spriteAt(14, 9)
	s.TwoHeadedOgre = spriteAt(15, 9)

	//Row Index 10
	s.RedChampion = spriteAt(0, 10)
	s.BlueChampion = spriteAt(1, 10)
	s.Caveman = spriteAt(2, 10)
	s.RockCollector = spriteAt(3, 10)
	s.RedMan = spriteAt(4, 10)
	s.Cursor = spriteAt(5, 10)
	s.EnemyCursor = spriteAt(6, 10)
	s.NullSprite = spriteAt(7, 10)
	s.FireBurst = spriteAt(8, 10)
	s.FireBurst2 = spriteAt(9, 10)
	s.FireBurst3 = spriteAt(10, 10)
	s.ArcaneBurst = spriteAt(11, 10)
	s.ArcaneBurst2 = spriteAt(12, 10)
	s.ArcaneBurst3 = spriteAt(13, 10)
	s.PosionBurst = spriteAt(14, 10)
	s.PosionBurst2 = spriteAt(15, 10)

	//Row Index 11
	s.PosionBurst3 = spriteAt(0, 11)
	s.Smoke = spriteAt(1, 11)
	s.BlueSmoke = spriteAt(2, 11)
	s.BigSmoke = spriteAt(3, 11)
	s.Smoke2 = spriteAt(4, 11)
	s.PurpleSmoke = spriteAt(5, 11)
	s.Trap = spriteAt(6, 11)

	return s, nil
}
