name: Build and Upload Cross-Platform Go Binary

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Name of the build binary'
        required: true
        default: 'Dungeoneer-v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]  # Add more architectures like arm64 if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go binary for ${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          BINARY_NAME="${{ inputs.build_name }}-${GOOS}-${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          go mod tidy
          go build -o $BINARY_NAME .
          echo "Built $BINARY_NAME"
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            ${{ inputs.build_name }}-${{ matrix.goos }}-${{ matrix.goarch }}*