name: Build and Upload Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Change this to your project's Go version

      - name: Build Go binary
        run: |
          go mod tidy
          go build -o Dungeoneer .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dungeoneer-binary
          path: ./Dungeoneer