name: Build and Upload Go Binary (Windows Only)

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Name of the build binary'
        required: true
        default: 'Dungeoneer-Stable-v1'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOS: windows
      GOARCH: amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Windows binary
        run: |
          go mod tidy
          OUTPUT_NAME="${{ inputs.build_name }}-${GOOS}-${GOARCH}.exe"
          go build -o $OUTPUT_NAME .
          echo "Built $OUTPUT_NAME"
        shell: bash

      - name: Upload Windows binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_name }}-${{ env.GOOS }}-${{ env.GOARCH }}
          path: ${{ inputs.build_name }}-${{ env.GOOS }}-${{ env.GOARCH }}.exe